[package]
name = "sheets-backend"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
edition = "2018"

[dependencies]
failure = "*"
futures = "0.1"
futures-cpupool = "*"
hyper = "^0.10"
hyper-rustls = "^0.6"
yup-oauth2 = "*"
google-sheets4 = "*"
